CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'scakmak'@'%' IDENTIFIED BY 'force99';
GRANT ALL PRIVILEGES ON wordpress.* TO 'scakmak'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootforce99';